POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "447589",
    "password": "keru0822009!"
}
###

GET http://localhost:5000/get-user
Cookie: access_token=
# set the token in access_token= that you get after login
###