
GET http://localhost:5000/roles
###
POST http://localhost:5000/create-role
Content-Type: application/json

{
    "name": "Create Role",
    "permission": "about this role" // eg. This role can do this, do that...
}
###
PUT http://localhost:5000/update-role/67192312d87304d47c011ab0
Content-Type: application/json

{
    "name": "Update Role",
    "permission": "updated role"
}
###
DELETE http://localhost:5000/delete-role/67172e40dc79a8fb90784365



### 
# FOR ASSIGNING ROLES TO USER
POST http://localhost:5000/assign-role
Content-Type: application/json

{
    "assignedBy": "447589", // current user's 6 digit(username)
    "user": "447589",
    "roles": [
        "67192312d87304d47c011ab0" // id of role
    ]
}
